# 6.5. Custom Layers

## 📘 Code Along

In [1]:
import torch
from torch import nn
from torch.nn import functional as F

### 6.5.1. Layers without Parameters

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

In [5]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(0., grad_fn=<MeanBackward0>)

### 6.5.2. Layers with Parameters

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [7]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.2792, -0.9963, -0.0118],
        [ 0.0670, -0.4133,  1.0051],
        [-0.4774,  0.7286,  0.3779],
        [-0.1858,  0.5521,  1.3823],
        [ 0.0490, -2.1272, -0.7223]], requires_grad=True)

In [8]:
linear(torch.rand(2, 5))

tensor([[0.6212, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.6266]])

In [9]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.0000],
        [2.6439]])