# 6.7. GPUs

## 📘 Code Along

In [2]:
import torch
from torch import nn

### 6.7.1. Computing Devices

In [4]:
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print(x)
else:
    print("MPS device not found.")

tensor([1.], device='mps:0')


In [5]:
torch.mps.device_count()

1

### 6.7.2. Tensors and GPUs

In [6]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [7]:
X = torch.ones(2, 3, device=mps_device)
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='mps:0')

### 6.7.3. Neural Networks and GPUs

In [8]:
net = nn.Sequential(nn.LazyLinear(1))
net = net.to(device=mps_device)

In [9]:
net(X)

tensor([[-0.5942],
        [-0.5942]], device='mps:0', grad_fn=<LinearBackward0>)

In [10]:
net[0].weight.data.device

device(type='mps', index=0)