In [2]:
import torch

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
x.numel()

12

In [7]:
x.shape

torch.Size([12])

In [9]:
X = x.reshape(3, 4)
X = x.reshape(-1, 4)
X = x.reshape(3, -1)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
torch.zeros(2, 3, 4)
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
torch.randn(3, 4)

tensor([[-1.2021e-01,  1.8838e+00, -5.4457e-01, -7.6449e-02],
        [ 1.4759e-03, -9.5609e-01, -2.4451e-01, -6.7968e-01],
        [-9.9591e-01,  3.0870e-01,  8.5520e-01,  4.3757e-01]])

In [13]:
torch.tensor([[2, 3, 4, 1], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 3, 4, 1],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])